version: '3.8'

services:
  backend:
    image: campuscore-backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb+srv://Admin:Admin@cluster0.9zjhb.mongodb.net/school-management-system
    volumes:
      - ./backend:/app
      - /app/node_modules
  
  frontend:
    image: campuscore-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BASE_URL=http://localhost:5000

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Admin
      - MONGO_INITDB_ROOT_PASSWORD=Admin
      - MONGO_INITDB_DATABASE=school-management-system

volumes:
  mongo_data: